### PR TITLE
 Setup SourceCred

### PR DESCRIPTION
**Pull request by hisergiorojas**

### CODE REVIEW

**Comment by shopifymia** [comment]
Hi Sergio, I added you as an admin for the project! Couldn't text you in discord, so writing in here. Thank you for starting this work; excited to review this PR 🤝

**Comment by bt3gl** [comment]
Hi Sergio, I added you as an admin for the project! Couldn't text you in discord, so writing in here. Thank you for starting this work; excited to review this PR 🤝

**Comment by hisergiorojas** [comment]
Screenshot from 2021-11-20 19-49-03

**Comment by hisergiorojas** [comment]
Screenshot from 2021-11-20 19-49-08

**Comment by hisergiorojas** [comment]
Screenshot from 2021-11-20 19-51-38

**Comment by hisergiorojas** [comment]
I'm not authorized to configure source cred to access the Discord server. I followed the instruction from https://sourcecred.io/docs/beta/plugins/discord/#configuration

**Review by bt3gl — APPROVED** [review]
🛳

**Comment by IxaBrjnko** [comment]
If we do not want to use gated channels for discord polls with tracking in sourcecred for Season 0 this is good and gets us started with tracking on github.  We can always add the module later.

**Pull request merged**
